spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dvd
    username: wfrp
    password: wfrp
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
        cache:
          use_query_cache: true
          use_second_level_cache: false
          hazelcast:
            use_native_client: false
          region:
            factory_class: com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory
